kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewers-binding-external
  namespace: "test6"
subjects:
- kind: Group
  name: k8s-namespace-viewer-k8s-test6-external
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io